name: bootpay_webview_flutter_example
description: Demonstrates how to use the bootpay_webview_flutter plugin.
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.6
  bootpay_webview_flutter:
    # When depending on this package from a real application you should use:
    #   bootpay_webview_flutter: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  bootpay_webview_flutter_android: 3.6.3
  bootpay_webview_flutter_wkwebview: ^3.4.1

dev_dependencies:
  build_runner: ^2.1.5
  espresso: ^0.2.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bootpay_webview_flutter_platform_interface: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_audio.ogg
    - assets/sample_video.mp4
    - assets/www/index.html
    - assets/www/styles/style.css
